import Link from "next/link"

export const head = () => {
  return (
    <>
        <title>My new head</title>
        <meta content="width=device-width, initial-scale=1" name="viewport"/>
        <meta name="description" content="Generated by create next app"/>
        <Link rel="icon" href="/favicon.ico" />
    </>
  )
}
